---
driver:
  name: docker
  use_sudo: false
  privileged: true
  provision_command:
    - systemctl enable sshd || true

provisioner:
  name: chef_infra
  chef_license: accept
  product_name: chef
  product_version: 16
  multiple_converge: 2
  enforce_idempotency: true
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
    driver_config:
      run_command: /usr/lib/systemd/systemd
  - name: ubuntu-22.04
    driver_config:
      run_command: /usr/lib/systemd/systemd
  - name: debian-11
    driver_config:
      run_command: /usr/lib/systemd/systemd
  - name: centos-stream-8
    driver_config:
      run_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[r-language::default]
    attributes:
      r-language:
        install_method: package
        install_dev: true
        packages: []
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/package

  - name: source
    run_list:
      - recipe[r-language::default]
    attributes:
      r-language:
        install_method: source
        version: '4.3.1'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/source

  - name: packages
    run_list:
      - recipe[r-language::default]
    attributes:
      r-language:
        install_method: package
        packages:
          - dplyr
          - ggplot2
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/package
        - test/integration/packages