AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - '.kitchen/**/*'
    - 'bin/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 40

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes