source 'https://rubygems.org'

gem 'chef', '~> 16.0'
gem 'chefspec', '~> 9.0'
gem 'kitchen-inspec', '~> 2.0'
gem 'kitchen-docker', '~> 2.12'
gem 'rake', '~> 13.0'
gem 'rubocop', '~> 1.0'
gem 'test-kitchen', '~> 3.0'
gem 'cookstyle', '~> 7.0'
gem 'inspec', '~> 5.18'